title: Igor Geller
logo: ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSonGKCfvk8fUSykyOwt818jVvKTFoLO7IfjPVu5epxlECeM1ecRh6BG6KdbuEJ30BANeA&usqp=CAU)
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
